### ISSUE TITLE
get autogenerated orderplates functioning

### ISSUE THREAD

**Issue by OliviaSimpson** [Waztom/xchem-CAR#47]
currently auto generated order plates is using placeholders for concentration, mcule id and plate name
initial commit of csv generator: pull request #46

**Comment by Waztom** [comment]
this is working for now. Will need to review when we start dealing with multi-inputs. Also need to consider that MCule will not always be able to supply the compounds. For now, we can leave the well address empty. In the future, accepting any input plate instead of hardcoding one will probably be the way to go - this will be heavily linked to how we deal with the multiple inputs/outputs.
